#!/bin/bash

#PBS -N run_data_processing_m12b
#PBS -l select=1:ncpus=1:mem=16gb
#PBS -l walltime=10:00:00
#PBS -M f.pal@unsw.edu.au
#PBS -m bae
#PBS -j oe
#PBS -o ../reports/output_reports
#PBS -e ../reports/error_reports

#PBS -J 0-100
## ${PBS_ARRAY_INDEX}

cd $PBS_O_WORKDIR
source ../my_env/bin/activate

python3 ../src/run_data_processing.py --simulation=m12b --iteration=${PBS_ARRAY_INDEX} --location=katana
