#!/bin/bash

#PBS -N run_gc_model_m12m
#PBS -l select=1:ncpus=1:mem=16gb
#PBS -l walltime=10:00:00
#PBS -M f.pal@unsw.edu.au
#PBS -m bae
#PBS -j oe
#PBS -o ../reports/output_reports
#PBS -e ../reports/error_reports

#PBS -J 101-220
## ${PBS_ARRAY_INDEX}

cd $PBS_O_WORKDIR
source ../my_env/bin/activate

python3 ../src/run_gc_model.py --simulation=m12m --iteration=${PBS_ARRAY_INDEX} --location=katana
